### GET one hammer by Id
GET http://localhost:8080/api/hammer/2

### GET all Hammers
GET http://localhost:8080/api/hammer/all


### Create a Hammer
POST http://localhost:8080/api/hammer/create
Content-Type: application/json

{
  "bezeichnung":"01/02/2024",
  "preis":3.99
}