### GET one hammer by Id
GET http://localhost:8080/api/hammer/2

### GET all Hammers
GET http://localhost:8080/api/hammer/all


### Create a Hammer
POST http://localhost:8080/api/hammer/create
Content-Type: application/json

{
  "id": 1,
  "bezeichnung": "Hammer",
  "preis": 10.0,
  "quality": 1,
  "color": "RED",
  "ipSchutz": 67
}